name: Go Linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run golangci-lint with reviewdog
      uses: reviewdog/action-golangci-lint@v2.0.3
