name: Go Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run golangci-lint with reviewdog
        uses: reviewdog/action-golangci-lint@v2.1.6
